### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by musicboy9** [musicboy9/fl_2023_grad#33]
- [ ] user option을 json 파일이 아닌 GUI에서 선택하도록 변경
- [ ] 수정한 flower library file을 새롭게 배포하여 다른 사요자가 requirements.txt를 통해 설치할 수 있도록 수정 (#32)
- [ ] status dict의 log / option 기능을 분리. dictionary가 아닌 customized class가 필요 (#21)
- [ ] Ray를 이용해서 client의 CPU, GPU, memory 자원을 더 세부적으로 조정 (#22)
